### ISSUE TITLE
Is there any way to set path to .luacheckrc file?

### ISSUE THREAD

**Issue by iluxaua** [AtomLinter/linter-luacheck#38]
Hello, I want to configurate linter to use external .luacheckrc file, that is placed not "in project root and/or Lua source dirs".
Is there any way to do it?
I didn't find any way to set path to .luacheckrc or set additional arguments.

**Comment by Positive07** [comment]
Since Luacheck 0.20.0 there is a [Global configuration file](http://luacheck.readthedocs.io/en/stable/config.html).
> `%LOCALAPPDATA%\Luacheck\.luacheckrc` on Windows
> `~/Library/Application Support/Luacheck/.luacheckrc` on OS X/macOS
> `$XDG_CONFIG_HOME/luacheck/.luacheckrc` or `~/.config/luacheck/.luacheckrc` on other systems by default.

Using a file that is in a non-standard path is not recommended, and won't be supported by this package.

Also as discussed in #33 your `.luacheckrc` should be the only thing that modifies the Linter configuration, otherwise you get undefined or erroneous behaviours. This file should always be included in your project in order to easily replicate your setup

**Comment by iluxaua** [comment]
@Positive07 thank you!

**Comment by Positive07** [comment]
No problem! I hope my answer, helped you
